### ISSUE TITLE
:)

### ISSUE THREAD

**Issue by redactedontop** [ClaraCrazy/qubes-docs#1]
Heya, Clara.
What if I point out you're a narcissist and a control freak? I guess you won't like that.

I'm so sad that your plan to erradicate Luna didn't work.
And as my final words for now: WOMP TO THE FUCKING WOMP

**Comment by ClaraCrazy** [comment]
who or whats luna?

**Comment by ClaraCrazy** [comment]
but  yeah.. https://womp-wo.mp

**Comment by redactedontop** [comment]
Don't kiss me UwU

**Comment by redactedontop** [comment]
And I was talking abt Luna Grabber haha..

**Comment by redactedontop** [comment]
https://github.com/Smug246/Luna-Grabber/issues/2
